### ISSUE TITLE
[Suggestion] Add CraftTweaker support for Roots Classic.

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [PrinceOfAmber/RootsClassic#10]
Hi, I'm making a modpack with Roots Classic and we found, thats the Roots Classic missing CraftTweaker support, so we need one. (In discord, you answered, that we need to make github issue with details)
What me and others exactly need?
1. **Ability to add and remove spell recipes with Mortar and Pestle**
2. **Ability to add and remove ritual recipes for Rituals**

I would be great to see CT support for it. Thank you in advance.

**Comment by PrinceOfAmber** [comment]
Yes some people have requested this as well.  I have started working in it, HOPEFULLY it is done within a week from today, 

..or if not everything then at least the mortar and pestle first and release that, and then rituals after as they might be a bit more complicated.

**Comment by PrinceOfAmber** [comment]
Added in latest release . Report anything else you find :) 
https://minecraft.curseforge.com/projects/roots-classic/files/2599066

**Comment by DenisMasterHerobrine** [comment]
Thanks :)
