### ISSUE TITLE
Crash while starting the game

### ISSUE THREAD

**Issue by zEpiixz** [PrinceOfAmber/RootsClassic#3]
https://pastebin.com/Bxu7L8hP

**Comment by kuroyure** [comment]
im having this problem too

**Comment by kuroyure** [comment]
any idea of how to solve it ?

**Comment by zEpiixz** [comment]
No thats why im here ^^

**Comment by PrinceOfAmber** [comment]
Crash only happens when ERZ is installed as well https://minecraft.curseforge.com/projects/emberroot-zoo and also it only happens with Roots 1.0.2, 

Fix coming tonight in 1.0.3
