### ISSUE TITLE
Healing standing stone and speed standing stone

### ISSUE THREAD

**Issue by Kazeindel** [PrinceOfAmber/RootsClassic#4]
When crafting the healing standing stone via ritual, it instead gave me a normal standing stone- one you use fro decoration by dying it.

The speed standing stone did not increase speed while in the area of effect.

**Comment by PrinceOfAmber** [comment]
Hey thanks for your patience, i am working on this :)

**Comment by PrinceOfAmber** [comment]
Fixed in latest release . Report anything else you find :) 
https://minecraft.curseforge.com/projects/roots-classic/files/2599066
